### PR TITLE
batched/dense: Reduce register pressure

### LINKED ISSUE #1547: Rocm/5.2 test failure with MI100 arch: hip.batched_scalar_batched_gemm_t_t_dcomplex_dcomplex_left
The `hip.batched_scalar_batched_gemm_t_t_dcomplex_dcomplex_left` test fails in builds with rocm/5.2:

Output snip:
```
[ RUN      ] hip.batched_scalar_batched_gemm_nt_nt_dcomplex_dcomplex_right
/home/ndellin/kokkos-kernels/test_common/KokkosKernels_TestUtils.hpp:139: Failure
Expected: ((double)AT1::abs(val1 - val2)) <= ((double)AT3::abs(tol)), actual: inf vs 2.22045e-13
  > from /home/ndellin/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp:impl_test_batched_gemm_with_handle:110
    > algo_type:BaseHeuristicAlgos::SQUARE, N:1, A:32x32, B:32x32, C:32x32

/home/ndellin/kokkos-kernels/test_common/KokkosKernels_TestUtils.hpp:139: Failure
Expected: ((double)AT1::abs(val1 - val2)) <= ((double)AT3::abs(tol)), actual: inf vs 2.22045e-13
  > from /home/ndellin/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp:impl_test_batched_gemm_with_handle:110
    > algo_type:BaseHeuristicAlgos::SQUARE, N:1, A:32x32, B:32x32, C:32x32
...
```

**Reproducer** (caraway MI100 queue):
```bash
module load cmake/3.19.3 rocm/5.2.0

 $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Hip,Serial --arch=MI100 --compiler=hipcc --cxxflags="-O3  " --cxxstandard="17" --with-hip --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --no-examples
```

### PR DESCRIPTION
**Pull request by e10harvey**
Fixes #1547.

### CODE REVIEW

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930</h3>
<ul>
  <li>Build Num: 154</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight</h3>
<ul>
  <li>Build Num: 162</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC1020</h3>
<ul>
  <li>Build Num: 115</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC1020_Light_LayoutRight</h3>
<ul>
  <li>Build Num: 114</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_GCC1020</h3>
<ul>
  <li>Build Num: 77</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_INTEL19</h3>
<ul>
  <li>Build Num: 164</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CLANG1001</h3>
<ul>
  <li>Build Num: 213</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CLANG13CUDA10</h3>
<ul>
  <li>Build Num: 99</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_ARMPL2110_Tpls_ARMPL2030_GCC1020</h3>
<ul>
  <li>Build Num: 103</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: KOKKOSKERNELS (e10harvey/kokkos-kernels)</dt>
  <ul>
    <li>Branch: issue1547</li>
    <li>SHA: 9bdbe6953190f907b66ea406186d00b95e32b43e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: e10harvey
</details>

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 2 Hrs 30 Mins. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930</h3>
<ul>
  <li>Build Num: 154</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight</h3>
<ul>
  <li>Build Num: 162</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC1020</h3>
<ul>
  <li>Build Num: 115</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC1020_Light_LayoutRight</h3>
<ul>
  <li>Build Num: 114</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_GCC1020</h3>
<ul>
  <li>Build Num: 77</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_INTEL19</h3>
<ul>
  <li>Build Num: 164</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CLANG1001</h3>
<ul>
  <li>Build Num: 213</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CLANG13CUDA10</h3>
<ul>
  <li>Build Num: 99</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_ARMPL2110_Tpls_ARMPL2030_GCC1020</h3>
<ul>
  <li>Build Num: 103</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>9bdbe6953190f907b66ea406186d00b95e32b43e</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930 # 154</b> (click to expand)
</summary>
<pre>
<code>
make: *** [all] Error 2
#######################################################
PASSED TESTS
#######################################################
#######################################################
FAILED TESTS
#######################################################
gcc-9.3.0-OpenMP-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 gcc/9.3.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=OpenMP --arch=Power8,Pascal60 --compiler=/home/projects/ppc64le/gcc/9.3.0/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=    --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930/KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930.154/TestAll_2022-11-14_19.53.48/gcc/9.3.0/OpenMP-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
gcc-9.3.0-OpenMP_Serial-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 gcc/9.3.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=OpenMP,Serial --arch=Power8,Pascal60 --compiler=/home/projects/ppc64le/gcc/9.3.0/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=    --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930/KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930.154/TestAll_2022-11-14_19.53.48/gcc/9.3.0/OpenMP_Serial-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
gcc-9.3.0-Serial-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 gcc/9.3.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Serial --arch=Power8,Pascal60 --compiler=/home/projects/ppc64le/gcc/9.3.0/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=    --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930/KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930.154/TestAll_2022-11-14_19.53.48/gcc/9.3.0/Serial-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
Build step 'Execute shell' marked build as failure
Finished: FAILURE

</code>
</pre>
</details>

<details>
<summary>
  <b>Console Output (last 100 lines) : KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight # 162</b> (click to expand)
</summary>
<pre>
<code>
/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp(306): here
            instantiation of "void test_batched_gemm_with_layout<ViewType,DeviceType,ValueType,ScalarType,ParamTagType>(int) [with ViewType=Kokkos::View<double ***, Kokkos::LayoutLeft, Kokkos::Cuda>, DeviceType=Kokkos::Cuda, ValueType=double, ScalarType=double, ParamTagType=Test::SharedParamTag<KokkosBlas::Trans::NoTranspose, KokkosBlas::Trans::NoTranspose, KokkosBatched::BatchLayout::Left>]" 
/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp(369): here
            instantiation of "int test_batched_gemm<DeviceType,ValueType,ScalarType,ParamTagType>() [with DeviceType=Kokkos::Cuda, ValueType=double, ScalarType=double, ParamTagType=Test::SharedParamTag<KokkosBlas::Trans::NoTranspose, KokkosBlas::Trans::NoTranspose, KokkosBatched::BatchLayout::Left>]" 
/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm_Real.hpp(247): here

/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp(528): error: expression must be a modifiable lvalue
          detected during:
            instantiation of "int KokkosBatched::BatchedGemm<ArgTransA,ArgTransB,ArgBatchSzDim,BatchedGemmHandleType,ScalarType,AViewType,BViewType,CViewType>(BatchedGemmHandleType *, ScalarType, const AViewType &, const BViewType &, ScalarType, const CViewType &) [with ArgTransA=KokkosBlas::Trans::NoTranspose, ArgTransB=KokkosBlas::Trans::NoTranspose, ArgBatchSzDim=KokkosBatched::BatchLayout::Left, BatchedGemmHandleType=KokkosBatched::BatchedGemmHandle, ScalarType=double, AViewType=Kokkos::View<double ***, Kokkos::LayoutLeft, Kokkos::Cuda>, BViewType=Kokkos::View<double ***, Kokkos::LayoutLeft, Kokkos::Cuda>, CViewType=Kokkos::View<double ***, Kokkos::LayoutLeft, Kokkos::Cuda>]" 
/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp(113): here
            instantiation of "void Test::impl_test_batched_gemm_with_handle<DeviceType,ViewType,ScalarType,ParamTagType>(KokkosBatched::BatchedGemmHandle *, int, int, int, int, int, int, int, ScalarType, ScalarType) [with DeviceType=Kokkos::Cuda, ViewType=Kokkos::View<double ***, Kokkos::LayoutLeft, Kokkos::Cuda>, ScalarType=double, ParamTagType=Test::SharedParamTag<KokkosBlas::Trans::NoTranspose, KokkosBlas::Trans::NoTranspose, KokkosBatched::BatchLayout::Left>]" 
/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp(254): here
            instantiation of "void Test::impl_test_batched_gemm<DeviceType,ViewType,ScalarType,ParamTagType>(int, int, int, int, int, int, int) [with DeviceType=Kokkos::Cuda, ViewType=Kokkos::View<double ***, Kokkos::LayoutLeft, Kokkos::Cuda>, ScalarType=double, ParamTagType=Test::SharedParamTag<KokkosBlas::Trans::NoTranspose, KokkosBlas::Trans::NoTranspose, KokkosBatched::BatchLayout::Left>]" 
/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp(306): here
            instantiation of "void test_batched_gemm_with_layout<ViewType,DeviceType,ValueType,ScalarType,ParamTagType>(int) [with ViewType=Kokkos::View<double ***, Kokkos::LayoutLeft, Kokkos::Cuda>, DeviceType=Kokkos::Cuda, ValueType=double, ScalarType=double, ParamTagType=Test::SharedParamTag<KokkosBlas::Trans::NoTranspose, KokkosBlas::Trans::NoTranspose, KokkosBatched::BatchLayout::Left>]" 
/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp(369): here
            instantiation of "int test_batched_gemm<DeviceType,ValueType,ScalarType,ParamTagType>() [with DeviceType=Kokkos::Cuda, ValueType=double, ScalarType=double, ParamTagType=Test::SharedParamTag<KokkosBlas::Trans::NoTranspose, KokkosBlas::Trans::NoTranspose, KokkosBatched::BatchLayout::Left>]" 
/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm_Real.hpp(247): here

Error limit reached.
100 errors detected in the compilation of "/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos-kernels/batched/dense/unit_test/backends/Test_Cuda_Batched_Dense.cpp".
Compilation terminated.
make[2]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_cuda.dir/build.make:90: batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_cuda.dir/backends/Test_Cuda_Batched_Dense.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1567: batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_cuda.dir/all] Error 2
[ 76%] Linking CXX executable KokkosKernels_batched_sla_openmp
[ 76%] Built target KokkosKernels_batched_sla_openmp
[ 76%] Linking CXX executable KokkosKernels_common_openmp
[ 76%] Built target KokkosKernels_common_openmp
[ 77%] Linking CXX executable KokkosKernels_batched_sla_cuda
[ 77%] Built target KokkosKernels_batched_sla_cuda
[ 77%] Linking CXX executable KokkosKernels_common_cuda
[ 77%] Built target KokkosKernels_common_cuda
[ 78%] Linking CXX executable KokkosKernels_blas_openmp
[ 78%] Built target KokkosKernels_blas_openmp
[ 78%] Linking CXX executable KokkosKernels_graph_openmp
[ 78%] Built target KokkosKernels_graph_openmp
[ 78%] Linking CXX executable KokkosKernels_blas_cuda
[ 78%] Built target KokkosKernels_blas_cuda
[ 78%] Linking CXX executable KokkosKernels_graph_cuda
[ 78%] Built target KokkosKernels_graph_cuda
[ 78%] Linking CXX executable KokkosKernels_sparse_openmp
[ 78%] Built target KokkosKernels_sparse_openmp
[ 79%] Linking CXX executable KokkosKernels_sparse_cuda
[ 79%] Built target KokkosKernels_sparse_cuda
make: *** [Makefile:146: all] Error 2
#######################################################
PASSED TESTS
#######################################################
#######################################################
FAILED TESTS
#######################################################
cuda-11.2.2-Cuda_OpenMP-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.21.2 cuda/11.2.2 openblas/0.3.20/gcc/9.3.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Cuda,OpenMP --arch=Volta70 --compiler=/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/kokkos/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --ldflags="" --with-cuda=/home/projects/ppc64le-pwr9-nvidia/spack-installs/cuda/11.2.2/gcc/8.3.1/base/uflzqtv  --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=    --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight/KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight.162/TestAll_2022-11-14_20.16.25/cuda/11.2.2/Cuda_OpenMP-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
Build step 'Execute shell' marked build as failure
Finished: FAILURE

</code>
</pre>
</details>

<details>
<summary>
  <b>Console Output (last 100 lines) : KokkosKernels_PullRequest_GCC1020 # 115</b> (click to expand)
</summary>
<pre>
<code>
[ 70%] Built target sparse_pcg
[ 71%] Linking CXX executable sparse_sptrsv_superlu
[ 71%] Built target sparse_sptrsv_superlu
[ 71%] Linking CXX executable KokkosKernels_batched_sla_openmp
[ 71%] Built target KokkosKernels_batched_sla_openmp
[ 71%] Linking CXX executable sparse_block_pcg
[ 72%] Built target sparse_block_pcg
[ 72%] Linking CXX executable sparse_spgemm
[ 72%] Linking CXX executable KokkosBatched_Test_GMRES
[ 72%] Built target sparse_spgemm
[ 72%] Built target KokkosBatched_Test_GMRES
[ 72%] Linking CXX executable KokkosKernels_common_openmp
[ 72%] Built target KokkosKernels_common_openmp
[ 73%] Linking CXX executable sparse_gs
[ 73%] Built target sparse_gs
[ 74%] Linking CXX executable KokkosKernels_graph_openmp
[ 74%] Built target KokkosKernels_graph_openmp
[ 74%] Linking CXX executable KokkosKernels_blas_openmp
[ 74%] Built target KokkosKernels_blas_openmp
[ 75%] Linking CXX executable KokkosKernels_sparse_openmp
[ 75%] Built target KokkosKernels_sparse_openmp
make: *** [all] Error 2
#######################################################
PASSED TESTS
#######################################################
#######################################################
FAILED TESTS
#######################################################
gcc-10.2.0-OpenMP-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 gcc/10.2.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=OpenMP --arch=SKX --compiler=/home/projects/x86-64/gcc/10.2.0/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=    --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_GCC1020/KokkosKernels_PullRequest_GCC1020.115/TestAll_2022-11-14_20.16.38/gcc/10.2.0/OpenMP-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
gcc-10.2.0-Threads_Serial-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 gcc/10.2.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Threads,Serial --arch=SKX --compiler=/home/projects/x86-64/gcc/10.2.0/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=    --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_GCC1020/KokkosKernels_PullRequest_GCC1020.115/TestAll_2022-11-14_20.16.38/gcc/10.2.0/Threads_Serial-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
srun: error: blake10: task 0: Exited with exit code 2
Build step 'Execute shell' marked build as failure
Finished: FAILURE

</code>
</pre>
</details>

<details>
<summary>
  <b>Console Output (last 100 lines) : KokkosKernels_PullRequest_GCC1020_Light_LayoutRight # 114</b> (click to expand)
</summary>
<pre>
<code>
[ 70%] Built target sparse_pcg
[ 71%] Linking CXX executable sparse_sptrsv_superlu
[ 71%] Built target sparse_sptrsv_superlu
[ 72%] Linking CXX executable sparse_spgemm
[ 72%] Linking CXX executable KokkosKernels_batched_sla_openmp
[ 72%] Built target sparse_spgemm
[ 72%] Built target KokkosKernels_batched_sla_openmp
[ 72%] Linking CXX executable KokkosBatched_Test_GMRES
[ 72%] Linking CXX executable sparse_block_pcg
[ 72%] Built target KokkosBatched_Test_GMRES
[ 72%] Built target sparse_block_pcg
[ 72%] Linking CXX executable KokkosKernels_common_openmp
[ 72%] Built target KokkosKernels_common_openmp
[ 73%] Linking CXX executable sparse_gs
[ 73%] Built target sparse_gs
[ 74%] Linking CXX executable KokkosKernels_graph_openmp
[ 74%] Built target KokkosKernels_graph_openmp
[ 74%] Linking CXX executable KokkosKernels_blas_openmp
[ 74%] Built target KokkosKernels_blas_openmp
[ 75%] Linking CXX executable KokkosKernels_sparse_openmp
[ 75%] Built target KokkosKernels_sparse_openmp
make: *** [all] Error 2
#######################################################
PASSED TESTS
#######################################################
#######################################################
FAILED TESTS
#######################################################
gcc-10.2.0-OpenMP-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 gcc/10.2.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=OpenMP --arch=SKX --compiler=/home/projects/x86-64/gcc/10.2.0/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutRight --with-tpls=    --with-options= --with-cuda-options=  --with-spaces=hostspace --no-examples   --no-default-eti

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_GCC1020_Light_LayoutRight/KokkosKernels_PullRequest_GCC1020_Light_LayoutRight.114/TestAll_2022-11-14_20.16.48/gcc/10.2.0/OpenMP-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
gcc-10.2.0-Threads_Serial-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 gcc/10.2.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Threads,Serial --arch=SKX --compiler=/home/projects/x86-64/gcc/10.2.0/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutRight --with-tpls=    --with-options= --with-cuda-options=  --with-spaces=hostspace --no-examples   --no-default-eti

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_GCC1020_Light_LayoutRight/KokkosKernels_PullRequest_GCC1020_Light_LayoutRight.114/TestAll_2022-11-14_20.16.48/gcc/10.2.0/Threads_Serial-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
srun: error: blake12: task 0: Exited with exit code 2
Build step 'Execute shell' marked build as failure
Finished: FAILURE

</code>
</pre>
</details>

<details>
<summary>
  <b>Console Output (last 100 lines) : KokkosKernels_PullRequest_Tpls_GCC1020 # 77</b> (click to expand)
</summary>
<pre>
<code>
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:528:44: error: assignment of read-only variable tile_k
  528 |           tile_m = 32, tile_n = 32, tile_k = 16;
      |                                     ~~~~~~~^~~~
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp: In instantiation of int KokkosBatched::BatchedGemm(BatchedGemmHandleType*, ScalarType, const AViewType&, const BViewType&, ScalarType, const CViewType&) [with ArgTransA = KokkosBlas::Trans::Transpose; ArgTransB = KokkosBlas::Trans::Transpose; ArgBatchSzDim = KokkosBatched::BatchLayout::Right; BatchedGemmHandleType = KokkosBatched::BatchedGemmHandle; ScalarType = Kokkos::complex<double>; AViewType = Kokkos::View<Kokkos::complex<double>***, Kokkos::LayoutLeft, Kokkos::Serial>; BViewType = Kokkos::View<Kokkos::complex<double>***, Kokkos::LayoutLeft, Kokkos::Serial>; CViewType = Kokkos::View<Kokkos::complex<double>***, Kokkos::LayoutLeft, Kokkos::Serial>]:
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp:111:52:   required from void Test::impl_test_batched_gemm_with_handle(KokkosBatched::BatchedGemmHandle*, int, int, int, int, int, int, int, ScalarType, ScalarType) [with DeviceType = Kokkos::Serial; ViewType = Kokkos::View<Kokkos::complex<double>***, Kokkos::LayoutLeft, Kokkos::Serial>; ScalarType = Kokkos::complex<double>; ParamTagType = Test::SharedParamTag<KokkosBlas::Trans::Transpose, KokkosBlas::Trans::Transpose, KokkosBatched::BatchLayout::Right>]
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp:252:59:   required from void Test::impl_test_batched_gemm(int, int, int, int, int, int, int) [with DeviceType = Kokkos::Serial; ViewType = Kokkos::View<Kokkos::complex<double>***, Kokkos::LayoutLeft, Kokkos::Serial>; ScalarType = Kokkos::complex<double>; ParamTagType = Test::SharedParamTag<KokkosBlas::Trans::Transpose, KokkosBlas::Trans::Transpose, KokkosBatched::BatchLayout::Right>]
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp:306:47:   required from void test_batched_gemm_with_layout(int) [with ViewType = Kokkos::View<Kokkos::complex<double>***, Kokkos::LayoutLeft, Kokkos::Serial>; DeviceType = Kokkos::Serial; ValueType = Kokkos::complex<double>; ScalarType = Kokkos::complex<double>; ParamTagType = Test::SharedParamTag<KokkosBlas::Trans::Transpose, KokkosBlas::Trans::Transpose, KokkosBatched::BatchLayout::Right>]
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm.hpp:369:46:   required from int test_batched_gemm() [with DeviceType = Kokkos::Serial; ValueType = Kokkos::complex<double>; ScalarType = Kokkos::complex<double>; ParamTagType = Test::SharedParamTag<KokkosBlas::Trans::Transpose, KokkosBlas::Trans::Transpose, KokkosBatched::BatchLayout::Right>]
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/kokkos-kernels/batched/dense/unit_test/Test_Batched_BatchedGemm_Complex.hpp:167:62:   required from here
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:528:18: error: assignment of read-only variable tile_m
  528 |           tile_m = 32, tile_n = 32, tile_k = 16;
      |           ~~~~~~~^~~~
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:528:31: error: assignment of read-only variable tile_n
  528 |           tile_m = 32, tile_n = 32, tile_k = 16;
      |                        ~~~~~~~^~~~
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:528:44: error: assignment of read-only variable tile_k
  528 |           tile_m = 32, tile_n = 32, tile_k = 16;
      |                                     ~~~~~~~^~~~
make[2]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_openmp.dir/backends/Test_OpenMP_Batched_Dense.cpp.o] Error 1
make[1]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_openmp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_serial.dir/backends/Test_Serial_Batched_Dense.cpp.o] Error 1
make[1]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_serial.dir/all] Error 2
[ 77%] Linking CXX executable KokkosKernels_batched_sla_openmp
[ 77%] Linking CXX executable KokkosKernels_batched_sla_serial
[ 77%] Built target KokkosKernels_batched_sla_openmp
[ 77%] Built target KokkosKernels_batched_sla_serial
[ 77%] Linking CXX executable KokkosKernels_common_serial
[ 77%] Built target KokkosKernels_common_serial
[ 77%] Linking CXX executable KokkosKernels_common_openmp
[ 77%] Built target KokkosKernels_common_openmp
[ 77%] Linking CXX executable KokkosKernels_graph_serial
[ 77%] Built target KokkosKernels_graph_serial
[ 77%] Linking CXX executable KokkosKernels_graph_openmp
[ 77%] Built target KokkosKernels_graph_openmp
[ 78%] Linking CXX executable KokkosKernels_blas_serial
[ 78%] Built target KokkosKernels_blas_serial
[ 78%] Linking CXX executable KokkosKernels_blas_openmp
[ 78%] Built target KokkosKernels_blas_openmp
[ 79%] Linking CXX executable KokkosKernels_sparse_openmp
[ 79%] Built target KokkosKernels_sparse_openmp
[ 79%] Linking CXX executable KokkosKernels_sparse_serial
[ 79%] Built target KokkosKernels_sparse_serial
make: *** [all] Error 2
#######################################################
PASSED TESTS
#######################################################
#######################################################
FAILED TESTS
#######################################################
gcc-10.2.0-OpenMP_Serial-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 gcc/10.2.0 openblas/0.3.21/gcc/10.2.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=OpenMP,Serial --arch=SKX --compiler=/home/projects/x86-64/gcc/10.2.0/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=blas --user-blas-path=/home/projects/x86-64-skylake/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-10.2.0/openblas-0.3.21-k3hscel2el5bpov4ejvsn5yl5atsezr6/lib --user-lapack-path=/home/projects/x86-64-skylake/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-10.2.0/openblas-0.3.21-k3hscel2el5bpov4ejvsn5yl5atsezr6/lib --user-blas-lib=blas --user-lapack-lib=lapack --extra-linker-flags=-lgfortran,-lm --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_GCC1020/KokkosKernels_PullRequest_Tpls_GCC1020.77/TestAll_2022-11-14_20.16.58/gcc/10.2.0/OpenMP_Serial-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
srun: error: blake13: task 0: Exited with exit code 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE

</code>
</pre>
</details>

<details>
<summary>
  <b>Console Output (last 100 lines) : KokkosKernels_PullRequest_Tpls_INTEL19 # 164</b> (click to expand)
</summary>
<pre>
<code>
[ 90%] Built target KokkosKernels_wiki_coarsening
[ 90%] Linking CXX executable KokkosKernels_wiki_coloring
[ 90%] Built target KokkosKernels_wiki_coloring
[ 91%] Linking CXX executable KokkosKernels_gmres_test_real_A
[ 91%] Built target KokkosKernels_gmres_test_real_A
[ 91%] Linking CXX executable KokkosKernels_batched_sla_threads
[ 92%] Linking CXX executable KokkosKernels_gmres_test_prec
[ 93%] Linking CXX executable gmres_ex_real_A
[ 93%] Built target KokkosKernels_batched_sla_threads
[ 93%] Built target KokkosKernels_gmres_test_prec
[ 93%] Built target gmres_ex_real_A
[ 94%] Linking CXX executable gmres_test_cmplx_A
[ 94%] Built target gmres_test_cmplx_A
[ 94%] Linking CXX executable KokkosKernels_common_threads
[ 94%] Built target KokkosKernels_common_threads
[ 94%] Linking CXX executable KokkosKernels_graph_threads
[ 94%] Built target KokkosKernels_graph_threads
[ 95%] Linking CXX executable KokkosKernels_blas_threads
[ 95%] Built target KokkosKernels_blas_threads
[ 96%] Linking CXX executable KokkosKernels_sparse_threads
[ 96%] Built target KokkosKernels_sparse_threads
make: *** [all] Error 2
#######################################################
PASSED TESTS
#######################################################
#######################################################
FAILED TESTS
#######################################################
intel-19.5.281-OpenMP-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 intel/compilers/19.5.281

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=OpenMP --arch=SKX --compiler=/home/projects/x86-64/intel/compilers/2019/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -diag-disable=1011 -diag-disable=869 -diag-disable=1011 -diag-disable=869" --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=mkl    --with-options= --with-cuda-options=   --no-examples   --disable-perftests

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_INTEL19/KokkosKernels_PullRequest_Tpls_INTEL19.164/TestAll_2022-11-14_20.17.09/intel/19.5.281/OpenMP-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
intel-19.5.281-Threads-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 intel/compilers/19.5.281

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Threads --arch=SKX --compiler=/home/projects/x86-64/intel/compilers/2019/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized -diag-disable=1011 -diag-disable=869 -diag-disable=1011 -diag-disable=869" --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=mkl    --with-options= --with-cuda-options=   --no-examples   --disable-perftests

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_Tpls_INTEL19/KokkosKernels_PullRequest_Tpls_INTEL19.164/TestAll_2022-11-14_20.17.09/intel/19.5.281/Threads-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
srun: error: blake14: task 0: Exited with exit code 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE

</code>
</pre>
</details>

<details>
<summary>
  <b>Console Output (last 100 lines) : KokkosKernels_PullRequest_CLANG1001 # 213</b> (click to expand)
</summary>
<pre>
<code>
          ~~~~~~ ^
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_CLANG1001/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:524:23: note: variable 'tile_m' declared const here
        constexpr int tile_m = 32, tile_n = 32, tile_k = 8;
        ~~~~~~~~~~~~~~^~~~~~~~~~~
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_CLANG1001/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:528:31: error: cannot assign to variable 'tile_n' with const-qualified type 'const int'
          tile_m = 32, tile_n = 32, tile_k = 16;
                       ~~~~~~ ^
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_CLANG1001/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:524:36: note: variable 'tile_n' declared const here
        constexpr int tile_m = 32, tile_n = 32, tile_k = 8;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_CLANG1001/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:528:44: error: cannot assign to variable 'tile_k' with const-qualified type 'const int'
          tile_m = 32, tile_n = 32, tile_k = 16;
                                    ~~~~~~ ^
/home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_CLANG1001/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:524:49: note: variable 'tile_k' declared const here
        constexpr int tile_m = 32, tile_n = 32, tile_k = 8;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
4 errors generated.
make[2]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_threads.dir/backends/Test_Threads_Batched_Dense.cpp.o] Error 1
make[1]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_threads.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
4 errors generated.
make[2]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_serial.dir/backends/Test_Serial_Batched_Dense.cpp.o] Error 1
make[1]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_serial.dir/all] Error 2
[ 76%] Linking CXX executable KokkosKernels_common_threads
[ 76%] Linking CXX executable KokkosKernels_batched_sla_threads
[ 77%] Linking CXX executable KokkosKernels_batched_sla_serial
[ 77%] Linking CXX executable KokkosKernels_common_serial
[ 77%] Built target KokkosKernels_batched_sla_threads
[ 77%] Built target KokkosKernels_batched_sla_serial
[ 77%] Built target KokkosKernels_common_threads
[ 77%] Built target KokkosKernels_common_serial
[ 77%] Linking CXX executable KokkosKernels_graph_threads
[ 77%] Built target KokkosKernels_graph_threads
[ 77%] Linking CXX executable KokkosKernels_graph_serial
[ 77%] Built target KokkosKernels_graph_serial
[ 78%] Linking CXX executable KokkosKernels_blas_threads
[ 78%] Built target KokkosKernels_blas_threads
[ 78%] Linking CXX executable KokkosKernels_blas_serial
[ 78%] Built target KokkosKernels_blas_serial
[ 78%] Linking CXX executable KokkosKernels_sparse_threads
[ 78%] Built target KokkosKernels_sparse_threads
[ 79%] Linking CXX executable KokkosKernels_sparse_serial
[ 79%] Built target KokkosKernels_sparse_serial
make: *** [all] Error 2
#######################################################
PASSED TESTS
#######################################################
#######################################################
FAILED TESTS
#######################################################
clang-10.0.1-Threads_Serial-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.19.3 clang/10.0.1

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Threads,Serial --arch=SKX --compiler=/home/projects/x86-64/spack/opt/spack/linux-rhel7-x86_64/gcc-10.2.0/llvm-10.0.1-nldepabrxk2zcykcq7rlky5sr53hnm63/bin/clang++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=    --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/blake-new/workspace/KokkosKernels_PullRequest_CLANG1001/KokkosKernels_PullRequest_CLANG1001.213/TestAll_2022-11-14_20.17.20/clang/10.0.1/Threads_Serial-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
srun: error: blake15: task 0: Exited with exit code 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE

</code>
</pre>
</details>

<details>
<summary>
  <b>Console Output (last 100 lines) : KokkosKernels_PullRequest_CLANG13CUDA10 # 99</b> (click to expand)
</summary>
<pre>
<code>
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CLANG13CUDA10/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:528:44: error: cannot assign to variable 'tile_k' with const-qualified type 'const int'
          tile_m = 32, tile_n = 32, tile_k = 16;
                                    ~~~~~~ ^
/home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CLANG13CUDA10/kokkos-kernels/batched/dense/src/KokkosBatched_Gemm_Decl.hpp:524:49: note: variable 'tile_k' declared const here
        constexpr int tile_m = 32, tile_n = 32, tile_k = 8;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
4 errors generated when compiling for sm_70.
make[2]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_serial.dir/build.make:90: batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_serial.dir/backends/Test_Serial_Batched_Dense.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1567: batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_serial.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
4 errors generated when compiling for sm_70.
make[2]: *** [batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_cuda.dir/build.make:90: batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_cuda.dir/backends/Test_Cuda_Batched_Dense.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1540: batched/dense/unit_test/CMakeFiles/KokkosKernels_batched_dla_cuda.dir/all] Error 2
[ 76%] Linking CXX executable KokkosKernels_batched_sla_serial
/home/projects/ppc64le/binutils/2.30.0/bin/ld: warning: libgfortran.so.5, needed by /home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib/liblapack.so, may conflict with libgfortran.so.4
[ 76%] Built target KokkosKernels_batched_sla_serial
[ 76%] Linking CXX executable KokkosKernels_common_serial
/home/projects/ppc64le/binutils/2.30.0/bin/ld: warning: libgfortran.so.5, needed by /home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib/liblapack.so, may conflict with libgfortran.so.4
[ 76%] Built target KokkosKernels_common_serial
[ 77%] Linking CXX executable KokkosKernels_batched_sla_cuda
/home/projects/ppc64le/binutils/2.30.0/bin/ld: warning: libgfortran.so.5, needed by /home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib/liblapack.so, may conflict with libgfortran.so.4
[ 77%] Built target KokkosKernels_batched_sla_cuda
[ 77%] Linking CXX executable KokkosKernels_common_cuda
/home/projects/ppc64le/binutils/2.30.0/bin/ld: warning: libgfortran.so.5, needed by /home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib/liblapack.so, may conflict with libgfortran.so.4
[ 77%] Built target KokkosKernels_common_cuda
[ 77%] Linking CXX executable KokkosKernels_graph_serial
/home/projects/ppc64le/binutils/2.30.0/bin/ld: warning: libgfortran.so.5, needed by /home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib/liblapack.so, may conflict with libgfortran.so.4
[ 77%] Built target KokkosKernels_graph_serial
[ 78%] Linking CXX executable KokkosKernels_blas_serial
/home/projects/ppc64le/binutils/2.30.0/bin/ld: warning: libgfortran.so.5, needed by /home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib/liblapack.so, may conflict with libgfortran.so.4
[ 78%] Built target KokkosKernels_blas_serial
[ 78%] Linking CXX executable KokkosKernels_blas_cuda
/home/projects/ppc64le/binutils/2.30.0/bin/ld: warning: libgfortran.so.5, needed by /home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib/liblapack.so, may conflict with libgfortran.so.4
[ 78%] Built target KokkosKernels_blas_cuda
[ 78%] Linking CXX executable KokkosKernels_graph_cuda
/home/projects/ppc64le/binutils/2.30.0/bin/ld: warning: libgfortran.so.5, needed by /home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib/liblapack.so, may conflict with libgfortran.so.4
[ 78%] Built target KokkosKernels_graph_cuda
[ 78%] Linking CXX executable KokkosKernels_sparse_serial
/home/projects/ppc64le/binutils/2.30.0/bin/ld: warning: libgfortran.so.5, needed by /home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib/liblapack.so, may conflict with libgfortran.so.4
[ 78%] Built target KokkosKernels_sparse_serial
[ 79%] Linking CXX executable KokkosKernels_sparse_cuda
/home/projects/ppc64le/binutils/2.30.0/bin/ld: warning: libgfortran.so.5, needed by /home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib/liblapack.so, may conflict with libgfortran.so.4
[ 79%] Built target KokkosKernels_sparse_cuda
make: *** [Makefile:146: all] Error 2
#######################################################
PASSED TESTS
#######################################################
#######################################################
FAILED TESTS
#######################################################
clang-13.0.0-Cuda-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        source /etc/profile.d/modules.sh
        module purge
        module load cmake/3.21.2 clang/13.0.0 openblas/0.3.20/gcc/9.3.0 cuda/10.1.243

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Cuda --arch=Power9,Volta70 --compiler=/home/projects/ppc64le-pwr9-nvidia/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/llvm-13.0.0-t6hzufjroylzhs7hg3dvmhrrcsvhygzv/bin/clang++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --ldflags="" --with-cuda=/home/projects/ppc64le-pwr9-nvidia/cuda/10.1.243  --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=blas --user-blas-path=/home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib --user-lapack-path=/home/projects/ppc64le-pwr9/spack/opt/spack/linux-rhel7-power9le/gcc-9.3.0/openblas-0.3.20-wt32he2mqdzpqfzdbyhiwaqibx6j6s3l/lib --user-blas-lib=blas --user-lapack-lib=lapack --extra-linker-flags=-lgfortran,-lm --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/weaver-new/workspace/KokkosKernels_PullRequest_CLANG13CUDA10/KokkosKernels_PullRequest_CLANG13CUDA10.99/TestAll_2022-11-14_20.20.59/clang/13.0.0/Cuda-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
Build step 'Execute shell' marked build as failure
Finished: FAILURE

</code>
</pre>
</details>

<details>
<summary>
  <b>Console Output (last 100 lines) : KokkosKernels_PullRequest_Tpls_ARMPL2110_Tpls_ARMPL2030_GCC1020 # 103</b> (click to expand)
</summary>
<pre>
<code>
[ 72%] Linking CXX executable sparse_spgemm
[ 72%] Built target sparse_spgemm
[ 72%] Linking CXX executable sparse_block_pcg
[ 72%] Built target sparse_block_pcg
[ 72%] Linking CXX executable KokkosKernels_batched_sla_serial
[ 72%] Built target KokkosKernels_batched_sla_serial
[ 72%] Linking CXX executable KokkosBatched_Test_GMRES
[ 72%] Built target KokkosBatched_Test_GMRES
[ 73%] Linking CXX executable sparse_gs
[ 73%] Built target sparse_gs
[ 73%] Linking CXX executable KokkosKernels_common_serial
[ 73%] Built target KokkosKernels_common_serial
[ 73%] Linking CXX executable sparse_sptrsv_supernode
[ 73%] Built target sparse_sptrsv_supernode
[ 74%] Linking CXX executable KokkosKernels_graph_serial
[ 74%] Built target KokkosKernels_graph_serial
[ 74%] Linking CXX executable KokkosKernels_blas_serial
[ 74%] Built target KokkosKernels_blas_serial
[ 75%] Linking CXX executable KokkosKernels_sparse_serial
[ 75%] Built target KokkosKernels_sparse_serial
make: *** [Makefile:158: all] Error 2
#######################################################
PASSED TESTS
#######################################################
#######################################################
FAILED TESTS
#######################################################
armpl-21.1.0-OpenMP-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        module purge
        module purge
        module load cmake/3.17.0 gcc/10.2.0 armpl/21.1.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=OpenMP --arch=A64FX --compiler=/opt/spatse/gcc/2020-09-17/spack/opt/spack/linux-rhel8-a64fx/gcc-8.2.1/gcc-10.2.0-f73mwr3ryd77o37a5jyofxet6nk7xowg/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=armpl    --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/inouye/workspace/workspace/KokkosKernels_PullRequest_Tpls_ARMPL2110_Tpls_ARMPL2030_GCC1020/KokkosKernels_PullRequest_Tpls_ARMPL2110_Tpls_ARMPL2030_GCC1020.103/TestAll_2022-11-14_20.23.03/armpl/21.1.0/OpenMP-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
armpl-21.1.0-Serial-release (build failed)
#######################################################
  # Reproducer instructions:
  #   Load modules:
        module purge
        module purge
        module load cmake/3.17.0 gcc/10.2.0 armpl/21.1.0

  #     $KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Serial --arch=A64FX --compiler=/opt/spatse/gcc/2020-09-17/spack/opt/spack/linux-rhel8-a64fx/gcc-8.2.1/gcc-10.2.0-f73mwr3ryd77o37a5jyofxet6nk7xowg/bin/g++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized " --cxxstandard="17" --ldflags=""   --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=armpl    --with-options= --with-cuda-options=   --no-examples  

  #  To reload modules, reconfigure, rebuild, and retest directly from this failing build do the following:
      # Move to the build directory
        cd /home/jenkins/inouye/workspace/workspace/KokkosKernels_PullRequest_Tpls_ARMPL2110_Tpls_ARMPL2030_GCC1020/KokkosKernels_PullRequest_Tpls_ARMPL2110_Tpls_ARMPL2030_GCC1020.103/TestAll_2022-11-14_20.23.03/armpl/21.1.0/Serial-release
      # To reload modules
        source ./reload_modules.sh
      # To reconfigure
        ./call_generate_makefile.sh
      # To rebuild
        make -j
      # To retest
        ctest -V
#######################################################
salloc: Relinquishing job allocation 2546
salloc: Job allocation 2546 has been revoked.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

</code>
</pre>
</details>

File: batched/dense/src/KokkosBatched_Gemm_Decl.hpp [hunk 1]
```diff
@@ -259,6 +259,42 @@ template <class ArgTransA, class ArgTransB, class ArgBatchSzDim,
...
+
+// On MI100, batched_scalar_batched_gemm_nt_nt_dcomplex_dcomplex_right fails
+// without this. See https://github.com/kokkos/kokkos-kernels/issues/1547.
+// This reduces the register allocations (REG_M and REG_N) in the double
+// buffering algorithm by a factor of 2.
+#if defined(KOKKOS_ENABLE_HIP) && defined(KOKKOS_ARCH_VEGA908)
+template <>
+constexpr KOKKOS_INLINE_FUNCTION int
+kk_gemm_dlb_buf_tile_k<Kokkos::Experimental::HIP>() {
+  return 16;
```
Comment (vqd8a) [inline batched/dense/src/KokkosBatched_Gemm_Decl.hpp:286]: @e10harvey I don't really follow. Please remind me. Why can tile_k=16 for HIP reduce the register allocation as compared to tile_k=8? Isn't that with tile_k=16 we have larger tile which needs more register? Am I missing something?

Comment (e10harvey) [reply batched/dense/src/KokkosBatched_Gemm_Decl.hpp:286]: `tile_k = 16` results in larger shared memory allocations but smaller REG_M and REG_N sizes:
https://github.com/kokkos/kokkos-kernels/blob/f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a/batched/dense/impl/KokkosBatched_Gemm_DblBuf_Impl.hpp#L385-L386

https://github.com/kokkos/kokkos-kernels/blob/f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a/batched/dense/impl/KokkosBatched_Gemm_DblBuf_Impl.hpp#L146-L147

Comment (vqd8a) [reply batched/dense/src/KokkosBatched_Gemm_Decl.hpp:286]: Thanks @e10harvey. Now I remember. :-)

**Review by vqd8a — APPROVED** [review]
Thanks @e10harvey. LGTM.

**Review by lucbv — APPROVED** [review]
Looks good to me and yeah register pressure on MI100 is a known issue... thanks for fixing this!

**Comment by e10harvey** [comment]
> Looks good to me and yeah register pressure on MI100 is a known issue...

@lucbv: Ah, is there somewhere I can read up on this?

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930</h3>
<ul>
  <li>Build Num: 159</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight</h3>
<ul>
  <li>Build Num: 167</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC1020</h3>
<ul>
  <li>Build Num: 120</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC1020_Light_LayoutRight</h3>
<ul>
  <li>Build Num: 119</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_GCC1020</h3>
<ul>
  <li>Build Num: 82</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_INTEL19</h3>
<ul>
  <li>Build Num: 169</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CLANG1001</h3>
<ul>
  <li>Build Num: 218</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CLANG13CUDA10</h3>
<ul>
  <li>Build Num: 104</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_ARMPL2110_Tpls_ARMPL2030_GCC1020</h3>
<ul>
  <li>Build Num: 108</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: KOKKOSKERNELS (e10harvey/kokkos-kernels)</dt>
  <ul>
    <li>Branch: issue1547</li>
    <li>SHA: 95c88e9e18e90d7e4d9940510ea6e58f2846d844</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: e10harvey
</details>

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC930_Light_Tpls_GCC930</h3>
<ul>
  <li>Build Num: 159</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CUDA11_CUDA11_LayoutRight</h3>
<ul>
  <li>Build Num: 167</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC1020</h3>
<ul>
  <li>Build Num: 120</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC1020_Light_LayoutRight</h3>
<ul>
  <li>Build Num: 119</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_GCC1020</h3>
<ul>
  <li>Build Num: 82</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_INTEL19</h3>
<ul>
  <li>Build Num: 169</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CLANG1001</h3>
<ul>
  <li>Build Num: 218</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CLANG13CUDA10</h3>
<ul>
  <li>Build Num: 104</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_ARMPL2110_Tpls_ARMPL2030_GCC1020</h3>
<ul>
  <li>Build Num: 108</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>issue1547</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/e10harvey/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>95c88e9e18e90d7e4d9940510ea6e58f2846d844</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>f3556c5c9791c3bc6e8f9d6e8c6b03d7322cc15a</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1588</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>
</details>

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ vqd8a lucbv ]!

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - This Repo does not support Automerge

**Comment by lucbv** [comment]
@e10harvey re-launching the github actions so we can have all the checks passing.
Regarding the register pressure, I do not know if you can easily read up on it but it is something that AMD mentioned more than once during hackathon and presentations about the MI100, I think it is a bit better on MI200 and higher...

**Comment by ndellingwood** [comment]
Candidate cherry-pick for release-candidate-3.7.01

**Comment by ndellingwood** [comment]
Cherry-picked to release-candidate-3.7.01 SHA 9b3b0457aed0f9598ae11210e55186ccbac95785
